name: Build mdbook

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1

      - run: mdbook build
